Applied UML Standards & simplified diagrams
mdebarros/documentation pull request #2
Opened 2019-03-21 13:35 UTC by ggrg

At some point of reviewing https://github.com/mojaloop/documentation/pull/3 I decided that it will be easier to submit this PR, than to continue on commenting and requesting changes on files which you haven't edited, but just changed paths.

2019-03-21 16:57 UTC, mdebarros requested changes
Thanks for this. Lots of visibility and consistency improvements. 

I do have a single issue for the callback line as per my comments.

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-participant-7.1.0.plantuml
> +    PAYER_FSP ->> ALS_API: Request to get participant's FSP details \nGET - /participants/{TYPE}/{ID}?currency={CURRENCY}\n<color #388724><b>Response code:</b> 202</color> \n<color #red><b>Error code
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-participant-7.1.0.plantuml
> +        ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{TYPE}/{ID}?currency={CURRENCY}
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-participant-7.1.0.plantuml
> +        ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{TYPE}/{ID}/error
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-parties-7.2.0.plantuml
> +    PAYER_FSP ->> ALS_API: Request to get parties's FSP details\nGET - /parties/{TYPE}/{ID}?currency={CURRENCY}\n<color #388724><b>Response code:</b> 202</color>\n<color #red><b>Error code:</b> 200zx
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-parties-7.2.0.plantuml
> +        ALS_PARTIES_FSP_DAO ->> PAYEE_FSP: Parties Callback to Destination:\nGET - /parties/{TYPE}/{ID}?currency={CURRENCY}\n<color #388724><b>Response code:</b> 202</color>\n<color #red><b>Error cod
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-parties-7.2.0.plantuml
> +        PAYEE_FSP ->> ALS_API: Callback with Participant Information:\nPUT - /parties/{TYPE}/{ID}?currency={CURRENCY}\n<color #red><b>Error code:</b> 200x, 300x, 310x, 320x</color>
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-parties-7.2.0.plantuml
> +        ALS_API ->> PAYER_FSP: Callback with Parties Information:\nPUT - /parties/{TYPE}/{ID}?currency={CURRENCY}
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-parties-7.2.0.plantuml
> +        ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{TYPE}/{ID}/error
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-get-parties-7.2.0.plantuml
> +        ALS_API ->> PAYEE_FSP: Callback: PUT - /participants/{TYPE}/{ID}/error
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-post-participants-7.2.1.plantuml
> +    PAYER_FSP ->> ALS_API: Request to add participant's FSP details\nPOST - /participants\n<color #388724><b>Response code:</b> 202</color> \n<color #FF0000><b>Error code:</b> 200x, 300x, 310x, 320x<
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-post-participants-7.2.1.plantuml
> +            ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{requestId}
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 16:57 UTC, mdebarros commented on mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-post-participants-7.2.1.plantuml
> +            ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{requestId}/error
We use '-->' to denote an async callback response in our other sequence diagrams do we not?

2019-03-21 17:05 UTC, ggrg commented
`We use '-->' to denote an async callback response in our other sequence diagrams do we not?`
Not really, we use '-->' to denote an async callback `Respond HTTP - 202 (Accepted)`.

2019-03-22 10:03 UTC, mdebarros approved these changes

2019-03-22 10:03 UTC, merged